/**
 * Generates supabase/seed.sql from the typed seed data, so the SQL can never
 * drift from the app's data model.
 *
 *   node --experimental-strip-types scripts/gen-seed.ts > supabase/seed.sql
 */
import { GLAZES } from "../src/lib/glazes.ts";
import { MEMBERS, PIECES } from "../src/lib/data.ts";

const q = (v: string | null | undefined) =>
  v == null ? "null" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const b = (v: boolean) => (v ? "true" : "false");
const arr = (v: string[] | undefined) =>
  v && v.length ? `ARRAY[${v.map(q).join(", ")}]::text[]` : `'{}'::text[]`;

const lines: string[] = [];
lines.push("-- WhatsGlazin seed data — GENERATED by scripts/gen-seed.ts. Do not edit by hand.");
lines.push("-- Run after schema.sql (Supabase SQL editor, or: psql < supabase/seed.sql).");
lines.push("begin;");
lines.push("");

lines.push("-- Members");
for (const m of MEMBERS) {
  lines.push(
    `insert into public.members (id, slug, name, avatar, member_since, disciplines) values ` +
      `(${q(m.id)}, ${q(m.slug)}, ${q(m.name)}, ${q(m.avatar)}, ${n(m.memberSince)}, ${arr(m.disciplines)}) ` +
      `on conflict (id) do update set slug=excluded.slug, name=excluded.name, avatar=excluded.avatar, member_since=excluded.member_since, disciplines=excluded.disciplines;`,
  );
}
lines.push("");

lines.push("-- Glazes (the studio's Cone 6 board)");
for (const g of GLAZES) {
  lines.push(
    `insert into public.glazes (id, slug, name, family, cone, base_hex, shade2_hex, on_color, finish, chemistry, description, is_studio_glaze) values ` +
      `(${q(g.id)}, ${q(g.slug)}, ${q(g.name)}, ${q(g.family)}, ${n(g.cone)}, ${q(g.baseHex)}, ${q(g.shade2Hex)}, ${q(g.onColor)}, ${q(g.finish)}, ${q(g.chemistry)}, ${q(g.description)}, ${b(g.isStudioGlaze)}) ` +
      `on conflict (id) do update set slug=excluded.slug, name=excluded.name, family=excluded.family, cone=excluded.cone, base_hex=excluded.base_hex, shade2_hex=excluded.shade2_hex, on_color=excluded.on_color, finish=excluded.finish, chemistry=excluded.chemistry, description=excluded.description, is_studio_glaze=excluded.is_studio_glaze;`,
  );
}
lines.push("");

lines.push("-- Demo pieces (illustrative; replaced by real uploads)");
for (const p of PIECES) {
  lines.push(
    `insert into public.pieces (id, slug, title, maker_id, form, clay_body, firing, notes) values ` +
      `(${q(p.id)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.makerId)}, ${q(p.form)}, ${q(p.clayBody)}, ${arr(p.firing)}, ${q(p.notes)}) ` +
      `on conflict (id) do update set slug=excluded.slug, title=excluded.title, maker_id=excluded.maker_id, form=excluded.form, clay_body=excluded.clay_body, firing=excluded.firing, notes=excluded.notes;`,
  );
  // reset + insert ordered glaze layers
  lines.push(`delete from public.piece_glazes where piece_id = ${q(p.id)};`);
  p.glazeIds.forEach((gid, i) => {
    lines.push(
      `insert into public.piece_glazes (piece_id, glaze_id, position) values (${q(p.id)}, ${q(gid)}, ${i});`,
    );
  });
}
lines.push("");
lines.push("commit;");

process.stdout.write(lines.join("\n") + "\n");
